table dim_date
	lineageTag: 69c67b5d-b460-4a75-bd23-dc4f8b853597

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: add2f871-c6d9-4b4a-8429-59dac077a507
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 618eacf1-6fe0-4513-911c-8b155d35f449
			defaultHierarchy: LocalDateTable_4206ab68-a673-4eee-b565-5879899d9900.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a4522436-6461-4243-87b9-7b3f037e9310
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: 684eab2f-a9d0-47f6-b4de-a426722cb7bb
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 4e689437-a28d-4265-8f21-f1331cb0568c
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Month number'
		dataType: int64
		formatString: 0
		lineageTag: a3bba9ca-f1c0-4684-91a5-01955369e667
		summarizeBy: sum
		sourceColumn: Month number

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    StartDate = #date(2026, 3, 1),
				    EndDate = #date(2026, 6, 30),
				    DateList = List.Dates(
				        StartDate,
				        Duration.Days(EndDate - StartDate) + 1,
				        #duration(1, 0, 0, 0)
				    ),
				    DateTable = Table.FromList(
				        DateList,
				        Splitter.SplitByNothing(),
				        {"date"}
				    ),
				    ChangedType = Table.TransformColumnTypes(
				        DateTable,
				        {{"date", type date}}
				    ),
				    AddYear = Table.AddColumn(
				        ChangedType,
				        "Year",
				        each Date.Year([date]),
				        Int64.Type
				    ),
				    AddMonthNumber = Table.AddColumn(
				        AddYear,
				        "Month number",
				        each Date.Month([date]),
				        Int64.Type
				    ),
				    AddMonth = Table.AddColumn(
				        AddMonthNumber,
				        "Month",
				        each Date.MonthName([date]),
				        type text
				    ),
				    AddDayName = Table.AddColumn(
				        AddMonth,
				        "Day Name",
				        each Date.DayOfWeekName([date]),
				        type text
				    )
				in
				    AddDayName

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

